// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: password
func (_m *PasswordHasher) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type PasswordHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//  - password string
func (_e *PasswordHasher_Expecter) HashPassword(password interface{}) *PasswordHasher_HashPassword_Call {
	return &PasswordHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *PasswordHasher_HashPassword_Call) Run(run func(password string)) *PasswordHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordHasher_HashPassword_Call) Return(_a0 string, _a1 error) *PasswordHasher_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// IsPasswordEqualToHash provides a mock function with given fields: password, hash
func (_m *PasswordHasher) IsPasswordEqualToHash(password string, hash string) bool {
	ret := _m.Called(password, hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PasswordHasher_IsPasswordEqualToHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPasswordEqualToHash'
type PasswordHasher_IsPasswordEqualToHash_Call struct {
	*mock.Call
}

// IsPasswordEqualToHash is a helper method to define mock.On call
//  - password string
//  - hash string
func (_e *PasswordHasher_Expecter) IsPasswordEqualToHash(password interface{}, hash interface{}) *PasswordHasher_IsPasswordEqualToHash_Call {
	return &PasswordHasher_IsPasswordEqualToHash_Call{Call: _e.mock.On("IsPasswordEqualToHash", password, hash)}
}

func (_c *PasswordHasher_IsPasswordEqualToHash_Call) Run(run func(password string, hash string)) *PasswordHasher_IsPasswordEqualToHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordHasher_IsPasswordEqualToHash_Call) Return(_a0 bool) *PasswordHasher_IsPasswordEqualToHash_Call {
	_c.Call.Return(_a0)
	return _c
}

type NewPasswordHasherT interface {
	mock.TestingT
	Cleanup(func())
}

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPasswordHasher(t NewPasswordHasherT) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
