// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	auth "github.com/grimerssy/go-example/pkg/auth"

	mock "github.com/stretchr/testify/mock"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// GenerateTokens provides a mock function with given fields: claims
func (_m *TokenManager) GenerateTokens(claims map[string]string) (auth.Tokens, error) {
	ret := _m.Called(claims)

	var r0 auth.Tokens
	if rf, ok := ret.Get(0).(func(map[string]string) auth.Tokens); ok {
		r0 = rf(claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Tokens)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_GenerateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokens'
type TokenManager_GenerateTokens_Call struct {
	*mock.Call
}

// GenerateTokens is a helper method to define mock.On call
//  - claims map[string]string
func (_e *TokenManager_Expecter) GenerateTokens(claims interface{}) *TokenManager_GenerateTokens_Call {
	return &TokenManager_GenerateTokens_Call{Call: _e.mock.On("GenerateTokens", claims)}
}

func (_c *TokenManager_GenerateTokens_Call) Run(run func(claims map[string]string)) *TokenManager_GenerateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *TokenManager_GenerateTokens_Call) Return(_a0 auth.Tokens, _a1 error) *TokenManager_GenerateTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ParseToken provides a mock function with given fields: token
func (_m *TokenManager) ParseToken(token auth.AccessToken) (map[string]string, error) {
	ret := _m.Called(token)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(auth.AccessToken) map[string]string); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(auth.AccessToken) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type TokenManager_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//  - token auth.AccessToken
func (_e *TokenManager_Expecter) ParseToken(token interface{}) *TokenManager_ParseToken_Call {
	return &TokenManager_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *TokenManager_ParseToken_Call) Run(run func(token auth.AccessToken)) *TokenManager_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.AccessToken))
	})
	return _c
}

func (_c *TokenManager_ParseToken_Call) Return(_a0 map[string]string, _a1 error) *TokenManager_ParseToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type NewTokenManagerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenManager(t NewTokenManagerT) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
