// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	auth "github.com/grimerssy/go-example/pkg/auth"

	mock "github.com/stretchr/testify/mock"
)

// TokenManager is an autogenerated mock type for the tokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// DefaultClaims provides a mock function with given fields:
func (_m *TokenManager) DefaultClaims() auth.Claims {
	ret := _m.Called()

	var r0 auth.Claims
	if rf, ok := ret.Get(0).(func() auth.Claims); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Claims)
		}
	}

	return r0
}

// TokenManager_DefaultClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultClaims'
type TokenManager_DefaultClaims_Call struct {
	*mock.Call
}

// DefaultClaims is a helper method to define mock.On call
func (_e *TokenManager_Expecter) DefaultClaims() *TokenManager_DefaultClaims_Call {
	return &TokenManager_DefaultClaims_Call{Call: _e.mock.On("DefaultClaims")}
}

func (_c *TokenManager_DefaultClaims_Call) Run(run func()) *TokenManager_DefaultClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenManager_DefaultClaims_Call) Return(_a0 auth.Claims) *TokenManager_DefaultClaims_Call {
	_c.Call.Return(_a0)
	return _c
}

// GenerateTokens provides a mock function with given fields: claims
func (_m *TokenManager) GenerateTokens(claims auth.Claims) (auth.Tokens, error) {
	ret := _m.Called(claims)

	var r0 auth.Tokens
	if rf, ok := ret.Get(0).(func(auth.Claims) auth.Tokens); ok {
		r0 = rf(claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Tokens)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(auth.Claims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_GenerateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokens'
type TokenManager_GenerateTokens_Call struct {
	*mock.Call
}

// GenerateTokens is a helper method to define mock.On call
//  - claims auth.Claims
func (_e *TokenManager_Expecter) GenerateTokens(claims interface{}) *TokenManager_GenerateTokens_Call {
	return &TokenManager_GenerateTokens_Call{Call: _e.mock.On("GenerateTokens", claims)}
}

func (_c *TokenManager_GenerateTokens_Call) Run(run func(claims auth.Claims)) *TokenManager_GenerateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.Claims))
	})
	return _c
}

func (_c *TokenManager_GenerateTokens_Call) Return(_a0 auth.Tokens, _a1 error) *TokenManager_GenerateTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ParseToken provides a mock function with given fields: token, claims
func (_m *TokenManager) ParseToken(token auth.AccessToken, claims auth.Claims) (auth.Claims, error) {
	ret := _m.Called(token, claims)

	var r0 auth.Claims
	if rf, ok := ret.Get(0).(func(auth.AccessToken, auth.Claims) auth.Claims); ok {
		r0 = rf(token, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Claims)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(auth.AccessToken, auth.Claims) error); ok {
		r1 = rf(token, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type TokenManager_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//  - token auth.AccessToken
//  - claims auth.Claims
func (_e *TokenManager_Expecter) ParseToken(token interface{}, claims interface{}) *TokenManager_ParseToken_Call {
	return &TokenManager_ParseToken_Call{Call: _e.mock.On("ParseToken", token, claims)}
}

func (_c *TokenManager_ParseToken_Call) Run(run func(token auth.AccessToken, claims auth.Claims)) *TokenManager_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.AccessToken), args[1].(auth.Claims))
	})
	return _c
}

func (_c *TokenManager_ParseToken_Call) Return(_a0 auth.Claims, _a1 error) *TokenManager_ParseToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type NewTokenManagerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenManager(t NewTokenManagerT) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
