// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Tokens is an autogenerated mock type for the Tokens type
type Tokens struct {
	mock.Mock
}

type Tokens_Expecter struct {
	mock *mock.Mock
}

func (_m *Tokens) EXPECT() *Tokens_Expecter {
	return &Tokens_Expecter{mock: &_m.Mock}
}

// AccessToken provides a mock function with given fields:
func (_m *Tokens) AccessToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Tokens_AccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessToken'
type Tokens_AccessToken_Call struct {
	*mock.Call
}

// AccessToken is a helper method to define mock.On call
func (_e *Tokens_Expecter) AccessToken() *Tokens_AccessToken_Call {
	return &Tokens_AccessToken_Call{Call: _e.mock.On("AccessToken")}
}

func (_c *Tokens_AccessToken_Call) Run(run func()) *Tokens_AccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tokens_AccessToken_Call) Return(_a0 string) *Tokens_AccessToken_Call {
	_c.Call.Return(_a0)
	return _c
}

type NewTokensT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTokens creates a new instance of Tokens. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokens(t NewTokensT) *Tokens {
	mock := &Tokens{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
