// Code generated by MockGen. DO NOT EDIT.
// Source: token.go

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// tokenMock is a mock of Token interface.
type tokenMock struct {
	ctrl     *gomock.Controller
	recorder *tokenMockMockRecorder
}

// tokenMockMockRecorder is the mock recorder for tokenMock.
type tokenMockMockRecorder struct {
	mock *tokenMock
}

// NewtokenMock creates a new mock instance.
func NewtokenMock(ctrl *gomock.Controller) *tokenMock {
	mock := &tokenMock{ctrl: ctrl}
	mock.recorder = &tokenMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *tokenMock) EXPECT() *tokenMockMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *tokenMock) AccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// AccessToken indicates an expected call of AccessToken.
func (mr *tokenMockMockRecorder) AccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*tokenMock)(nil).AccessToken))
}

// accessTokenMock is a mock of AccessToken interface.
type accessTokenMock struct {
	ctrl     *gomock.Controller
	recorder *accessTokenMockMockRecorder
}

// accessTokenMockMockRecorder is the mock recorder for accessTokenMock.
type accessTokenMockMockRecorder struct {
	mock *accessTokenMock
}

// NewaccessTokenMock creates a new mock instance.
func NewaccessTokenMock(ctrl *gomock.Controller) *accessTokenMock {
	mock := &accessTokenMock{ctrl: ctrl}
	mock.recorder = &accessTokenMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *accessTokenMock) EXPECT() *accessTokenMockMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *accessTokenMock) AccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// AccessToken indicates an expected call of AccessToken.
func (mr *accessTokenMockMockRecorder) AccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*accessTokenMock)(nil).AccessToken))
}
