CREATE TABLE users (
    id SERIAL NOT NULL,
    name VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_users_id PRIMARY KEY (id)
);
